version: '3'
services:
  frontend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/jacob-project/frontend:master
    command: "bash -c 'rm -rf /frontend/* && cp -r /app/build/* /frontend'"
    volumes:
      - frontend:/frontend

volumes:
  frontend:
    external: true

networks:
  default:
    external:
      name: jacob
